columns: 
- 'is_male': 'object'
- 'age': 'float64'
- 'category': 'object'
- 'quantiy': 'float64'
- 'price_per_unit': 'float64'
- 'cogs': 'float64'
- 'total_sale': 'int'

numerical_columns:
- age
- quantiy
- price_per_unit
- cogs  